backend:
  name: git-gateway
  branch: main

locale: 'pt-BR'
media_folder: "static/uploads"
public_folder: "./static/uploads"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
  - label: Ofertas
    name: offers
    folder: "src/_offers"
    extension: "json"
    create: true
    editor:
      preview: false
    identifier_field: name
    fields:
      - { label: Nome do produto, name: name, widget: string }
      - { label: Descrição, name: description, widget: text }
      - { label: Preço, name: fullPrice, widget: number, value_type: float }
      - label: Estoque
        name: stock
        widget: list
        summary: "Tamanho: {{size}} [{{count}}]"
        fields:
          - widget: string
            name: size
            label: Tamanho
          - widget: number
            name: count
            label: Quantidade
      - label: Imagens
        name: imageList
        widget: list
        fields:
          - widget: string
            name: alt
          - widget: image
            name: image
