backend:
  name: git-gateway
  branch: main

locale: 'pt-BR'
media_folder: "static/uploads"
public_folder: "./static/uploads"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
  - label: Ofertas
    name: offers
    folder: "src/_offers"
    extension: "json"
    create: true
    editor:
      preview: false
    identifier_field: name
    fields:
      - { label: Nome do produto, name: name, widget: string }
      - { label: Descrição, name: description, widget: text }
      - { label: "Preço cheio", name: fullPrice, widget: number, value_type: float }
      - { label: "Preço com desconto (0 para vender sem desconto)", name: offeredPrice, widget: number, value_type: float, default: 0 }
      - label: "Categoria"
        name: category
        widget: relation
        collection: configs
        file: categories
        search_fields: ["categories.*.category"]
        value_field: "categories.*.category"
      - label: Estoque
        name: stock
        widget: list
        summary: "Tamanho: {{size}} [{{count}}]"
        fields:
          - widget: string
            name: size
            label: Tamanho
          - widget: number
            name: count
            label: Quantidade
      - label: Imagens
        name: imageList
        widget: list
        fields:
          - widget: string
            label: Texto alternativo
            name: alt
          - widget: image
            label: Imagem
            name: src
  - label: Configurações
    name: configs
    extension: "json"
    editor:
      preview: false
    files:
      - label: "Categorias"
        name: categories
        file: "src/_data/categories.json"
        fields:
          - label: Lista de Categorias
            name: categories
            widget: list
            fields:
              - { label: Nome da categoria, name: category, widget: string }
