backend:
  name: git-gateway
  branch: main

locale: 'pt-BR'
media_folder: "static/uploads"
public_folder: "./static/uploads"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

collections:
  - label: Ofertas
    name: offers
    folder: "src/_offers"
    create: true
    editor:
      preview: false
    fields:
      - { label: Nome do produto, name: title, widget: string }
      - { label: Descrição, name: description, widget: text }
      - { label: Preço, name: fullPrice, widget: number }
      - label: Imagem
        name: image
        widget: image
      - label: Imagem2
        name: image2
        required: false
        widget: image
      - label: Imagem3
        name: image2
        required: false
        widget: image
      - label: Imagem4
        name: image2
        required: false
        widget: image
